### ISSUE TITLE
not working in windows 10 (Failed to load dynamic library (126))

### ISSUE THREAD

**Issue by learncodingforweb** [jpnurmi/libserialport.dart#37]
[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (126)
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)

```
import 'package:flutter/material.dart';
import 'package:libserialport/libserialport.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final name = SerialPort.availablePorts;
  
  @override
  Widget build(BuildContext context) {
    //print(name);
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: "Serial Port"),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'Serial Port Test on windows 10',
            ),            
          ],
        ),
      ),
    );
  }
}

```
using following yml
```
name: learn
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path: ^1.8.0
  libserialport: ^0.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
```
